SELECT a1.RITITLE , a2.PROTITLE , a3.WORKTITLE , a4.MNAME , a1.RCONTENT , a4.MCONTENT 
FROM risk a1, PROJECT a2, WORK a3, MANEUVER a4 
WHERE a1.PRONO = a2.PRONO AND a1.WORKNO = a3.WORKNO AND a1.PRONO =a4.PRONO AND a1.WORKNO = a4.WORKNO AND RISKNO = 0;


